# Generated by Django 3.2.8 on 2023-03-03 09:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20230303_1321'),
        ('property_owner', '0002_alter_property_property_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('trash', models.BooleanField(default=False)),
                ('special_request', models.TextField(max_length=2000, null=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 21, 9, 868568))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 21, 9, 868568))),
                ('guest_arrival_time', models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 3, 13, 21, 9, 868568))),
                ('reservation_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_createdby', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservation', to='core.userprofile')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_reservation', to='property_owner.property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
