# Generated by Django 3.2.8 on 2023-03-04 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20230303_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 12, 40, 37, 758468)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_arrival_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 4, 12, 40, 37, 758468)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 12, 40, 37, 758468)),
        ),
    ]
