# Generated by Django 3.2.8 on 2023-03-05 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_owner', '0004_roomoptions_number_of_beds'),
        ('client', '0011_auto_20230305_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ManyToManyField(related_name='room_reservation', to='property_owner.Room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 14, 14, 8, 756330)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_arrival_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 3, 5, 14, 14, 8, 756330)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 5, 14, 14, 8, 756330)),
        ),
    ]
