# Generated by Django 3.2.8 on 2023-03-03 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230303_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 21, 20, 907081)),
        ),
    ]
