# Generated by Django 3.2.8 on 2023-03-03 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 13, 22, 47, 747253)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.JSONField(default=dict),
        ),
    ]
