# Generated by Django 3.2.8 on 2023-03-03 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230303_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 23, 50, 17, 901253)),
        ),
    ]
