# Generated by Django 3.2.8 on 2023-03-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_photos',
            field=models.JSONField(default={}),
        ),
    ]
