# Generated by Django 3.2.8 on 2023-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_owner', '0002_alter_property_property_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_photos',
            field=models.JSONField(default=dict),
        ),
    ]
