# Generated by Django 3.2.8 on 2023-03-11 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property_owner', '0004_roomoptions_number_of_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='property_owner.propertytype'),
        ),
    ]
